-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-05-02 17:31:13 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called cui_schema_output.txt
set echo on
SPOOL cui_schema_output.txt

DROP TABLE bin CASCADE CONSTRAINTS;

DROP TABLE bin_collected CASCADE CONSTRAINTS;

DROP TABLE bin_type CASCADE CONSTRAINTS;

DROP TABLE collection CASCADE CONSTRAINTS;

DROP TABLE contract CASCADE CONSTRAINTS;

DROP TABLE contract_collection CASCADE CONSTRAINTS;

DROP TABLE contract_pricing CASCADE CONSTRAINTS;

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE driver_truck CASCADE CONSTRAINTS;

DROP TABLE local_authority CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE street CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE waste_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bin (
    bin_rfid      CHAR(16) NOT NULL,
    bin_date      DATE NOT NULL,
    bin_repreason CHAR(2),
    prop_id       NUMBER(7) NOT NULL,
    bt_size       NUMBER(4) NOT NULL,
    wt_id         CHAR(2) NOT NULL,
    contract_no   NUMBER(7) NOT NULL
);

ALTER TABLE bin
    ADD CONSTRAINT chk_binrepreason CHECK ( bin_repreason IN ( 'BF', 'OD', 'PD', 'ST'
    ) );

COMMENT ON COLUMN bin.bin_rfid IS
    'bin RFID as 16 characters hexadecimal number';

COMMENT ON COLUMN bin.bin_date IS
    'bin date supplied';

COMMENT ON COLUMN bin.bin_repreason IS
    'bin replacement reason (OD - Damaged by owner, BF - Bin Failure eg. old age, PD - Damaged during pickup, ST - Stolen)'
    ;

COMMENT ON COLUMN bin.prop_id IS
    'property id';

COMMENT ON COLUMN bin.bt_size IS
    'bin type size in litre';

COMMENT ON COLUMN bin.wt_id IS
    'waste type id';

COMMENT ON COLUMN bin.contract_no IS
    'contract number';

ALTER TABLE bin ADD CONSTRAINT bin_pk PRIMARY KEY ( bin_rfid );

CREATE TABLE bin_collected (
    collection_id NUMBER(7) NOT NULL,
    bin_rfid      CHAR(16) NOT NULL,
    bc_weight     NUMBER(5),
    bc_overweight CHAR(1 CHAR) NOT NULL
);

ALTER TABLE bin_collected
    ADD CONSTRAINT chk_bcoverweight CHECK ( bc_overweight IN ( 'N', 'Y' ) );

COMMENT ON COLUMN bin_collected.collection_id IS
    'collection id number (surrogate PK)';

COMMENT ON COLUMN bin_collected.bin_rfid IS
    'bin RFID as 16 characters hexadecimal number';

COMMENT ON COLUMN bin_collected.bc_weight IS
    'binn collected weight in kilograms, is not manditory';

COMMENT ON COLUMN bin_collected.bc_overweight IS
    'bin collected overweight (Y - Yes, N - No)';

ALTER TABLE bin_collected ADD CONSTRAINT bin_collected_pk PRIMARY KEY ( bin_rfid,
                                                                        collection_id
                                                                        );

CREATE TABLE bin_type (
    bt_size     NUMBER(4) NOT NULL,
    bt_suppcost NUMBER(6, 2) NOT NULL,
    wt_id       CHAR(2) NOT NULL
);

COMMENT ON COLUMN bin_type.bt_size IS
    'bin type size in litre';

COMMENT ON COLUMN bin_type.bt_suppcost IS
    'bin type supply cost';

COMMENT ON COLUMN bin_type.wt_id IS
    'waste type id';

ALTER TABLE bin_type ADD CONSTRAINT bin_type_pk PRIMARY KEY ( bt_size,
                                                              wt_id );

CREATE TABLE collection (
    collection_id   NUMBER(7) NOT NULL,
    contract_no     NUMBER(7) NOT NULL,
    wt_id           CHAR(2) NOT NULL,
    collection_date DATE NOT NULL,
    driver_no       NUMBER(7) NOT NULL,
    truck_vin       CHAR(17) NOT NULL
);

COMMENT ON COLUMN collection.collection_id IS
    'collection id number (surrogate PK)';

COMMENT ON COLUMN collection.contract_no IS
    'contract number';

COMMENT ON COLUMN collection.wt_id IS
    'waste type id';

COMMENT ON COLUMN collection.collection_date IS
    'The date that a collection has occured';

COMMENT ON COLUMN collection.driver_no IS
    'The driver number';

COMMENT ON COLUMN collection.truck_vin IS
    'truck VIN';

ALTER TABLE collection ADD CONSTRAINT collection_pk PRIMARY KEY ( collection_id );

ALTER TABLE collection
    ADD CONSTRAINT collection_nk UNIQUE ( contract_no,
                                          wt_id,
                                          collection_date );

CREATE TABLE contract (
    contract_no        NUMBER(7) NOT NULL,
    contract_startdate DATE NOT NULL,
    contract_enddate   DATE NOT NULL,
    la_name            VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN contract.contract_no IS
    'contract number';

COMMENT ON COLUMN contract.contract_startdate IS
    'contract start date';

COMMENT ON COLUMN contract.contract_enddate IS
    'contract_endDate';

COMMENT ON COLUMN contract.la_name IS
    'local authority name';

ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY ( contract_no );

CREATE TABLE contract_collection (
    contract_no  NUMBER(7) NOT NULL,
    wt_id        CHAR(2) NOT NULL,
    cc_costperkg NUMBER(6, 2) NOT NULL,
    cc_freq      CHAR(1) NOT NULL
);

ALTER TABLE contract_collection
    ADD CONSTRAINT chk_ccfreq CHECK ( cc_freq IN ( 'F', 'M', 'W' ) );

COMMENT ON COLUMN contract_collection.contract_no IS
    'contract number';

COMMENT ON COLUMN contract_collection.wt_id IS
    'waste type id';

COMMENT ON COLUMN contract_collection.cc_costperkg IS
    'contract collection cost per kg';

COMMENT ON COLUMN contract_collection.cc_freq IS
    'contract collection frequency (W - Weekly, F - Fortnightly, M - Monthly)';

ALTER TABLE contract_collection ADD CONSTRAINT contract_collection_pk PRIMARY KEY ( contract_no
,
                                                                                  wt_id
                                                                                  );

CREATE TABLE contract_pricing (
    contract_no    NUMBER(7) NOT NULL,
    bt_size        NUMBER(4) NOT NULL,
    wt_id          CHAR(2) NOT NULL,
    cp_supplyprice NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN contract_pricing.contract_no IS
    'contract number';

COMMENT ON COLUMN contract_pricing.bt_size IS
    'bin type size in litre';

COMMENT ON COLUMN contract_pricing.wt_id IS
    'waste type id';

COMMENT ON COLUMN contract_pricing.cp_supplyprice IS
    'contract supply price';

ALTER TABLE contract_pricing
    ADD CONSTRAINT contract_pricing_pk PRIMARY KEY ( bt_size,
                                                     wt_id,
                                                     contract_no );

CREATE TABLE driver (
    driver_no        NUMBER(7) NOT NULL,
    driver_licenceno NUMBER(9) NOT NULL,
    driver_name      VARCHAR2(50) NOT NULL,
    driver_dob       DATE NOT NULL,
    driver_tfn       NUMBER(9) NOT NULL,
    driver_contactno CHAR(10) NOT NULL
);

COMMENT ON COLUMN driver.driver_no IS
    'The driver number';

COMMENT ON COLUMN driver.driver_licenceno IS
    'driver licence number';

COMMENT ON COLUMN driver.driver_name IS
    'driver name';

COMMENT ON COLUMN driver.driver_dob IS
    'driver date of birth';

COMMENT ON COLUMN driver.driver_tfn IS
    'driver tax file number';

COMMENT ON COLUMN driver.driver_contactno IS
    'driver contact number';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_no );

CREATE TABLE driver_truck (
    driver_no   NUMBER(7) NOT NULL,
    truck_vin   CHAR(17) NOT NULL,
    dt_approval DATE NOT NULL
);

COMMENT ON COLUMN driver_truck.driver_no IS
    'The driver number';

COMMENT ON COLUMN driver_truck.truck_vin IS
    'truck VIN';

COMMENT ON COLUMN driver_truck.dt_approval IS
    'driver truck approval date';

ALTER TABLE driver_truck ADD CONSTRAINT driver_truck_pk PRIMARY KEY ( driver_no,
                                                                      truck_vin );

CREATE TABLE local_authority (
    la_name      VARCHAR2(50) NOT NULL,
    la_ceofname  VARCHAR2(30) NOT NULL,
    la_ceolname  VARCHAR2(30) NOT NULL,
    la_phoneno   VARCHAR2(10) NOT NULL,
    la_totalarea NUMBER(3) NOT NULL,
    la_type      CHAR(2) NOT NULL
);

ALTER TABLE local_authority
    ADD CONSTRAINT chk_latype CHECK ( la_type IN ( 'BO', 'CT', 'DC', 'SH', 'TN' ) );

COMMENT ON COLUMN local_authority.la_name IS
    'local authority name';

COMMENT ON COLUMN local_authority.la_ceofname IS
    'local authority CEO  first name';

COMMENT ON COLUMN local_authority.la_ceolname IS
    'local authority CEO last name';

COMMENT ON COLUMN local_authority.la_phoneno IS
    'local authority phone number';

COMMENT ON COLUMN local_authority.la_totalarea IS
    'local authority total area in square kilometers';

COMMENT ON COLUMN local_authority.la_type IS
    'local authority type (BO - Borough, CT - City, DC - District Council, SH - Shire, TN - Town)'
    ;

ALTER TABLE local_authority ADD CONSTRAINT local_authority_pk PRIMARY KEY ( la_name )
;

CREATE TABLE owner (
    owner_id      NUMBER(7) NOT NULL,
    owner_name    VARCHAR2(50) NOT NULL,
    owner_email   VARCHAR2(30) NOT NULL,
    owner_phoneno CHAR(10) NOT NULL,
    prop_id       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id';

COMMENT ON COLUMN owner.owner_name IS
    'owner name';

COMMENT ON COLUMN owner.owner_email IS
    'owner email';

COMMENT ON COLUMN owner.owner_phoneno IS
    'owner phone number';

COMMENT ON COLUMN owner.prop_id IS
    'property id';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE property (
    prop_id   NUMBER(7) NOT NULL,
    prop_stno VARCHAR2(4) NOT NULL,
    st_id     NUMBER(7) NOT NULL,
    la_name   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN property.prop_id IS
    'property id';

COMMENT ON COLUMN property.prop_stno IS
    'property street number';

COMMENT ON COLUMN property.st_id IS
    'street id';

COMMENT ON COLUMN property.la_name IS
    'local authority name';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_id );

ALTER TABLE property
    ADD CONSTRAINT property_nk UNIQUE ( prop_stno,
                                        st_id,
                                        la_name );

CREATE TABLE street (
    st_id          NUMBER(7) NOT NULL,
    la_name        VARCHAR2(50) NOT NULL,
    st_name        VARCHAR2(50) NOT NULL,
    st_length      NUMBER(5) NOT NULL,
    st_roadsurface CHAR(1) NOT NULL,
    st_nolanes     NUMBER(1) NOT NULL
);

ALTER TABLE street
    ADD CONSTRAINT chk_stroadsurface CHECK ( st_roadsurface IN ( 'A', 'C', 'U' ) );

COMMENT ON COLUMN street.st_id IS
    'street id';

COMMENT ON COLUMN street.la_name IS
    'local authority name';

COMMENT ON COLUMN street.st_name IS
    'street name';

COMMENT ON COLUMN street.st_length IS
    'street length in meters';

COMMENT ON COLUMN street.st_roadsurface IS
    'street road surface (A - Asphalt, C - Concrete, U - Unsealed)';

COMMENT ON COLUMN street.st_nolanes IS
    'street number of lanes';

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( st_id,
                                                          la_name );

CREATE TABLE truck (
    truck_vin   CHAR(17) NOT NULL,
    truck_rego  CHAR(9) NOT NULL,
    truck_make  VARCHAR2(30) NOT NULL,
    truck_model VARCHAR2(50) NOT NULL,
    truck_year  NUMBER(4) NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'truck VIN';

COMMENT ON COLUMN truck.truck_rego IS
    'truck registration number';

COMMENT ON COLUMN truck.truck_make IS
    'truck make';

COMMENT ON COLUMN truck.truck_model IS
    'truck model';

COMMENT ON COLUMN truck.truck_year IS
    'truck year of manufacture';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE waste_type (
    wt_id   CHAR(2) NOT NULL,
    wt_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN waste_type.wt_id IS
    'waste type id';

COMMENT ON COLUMN waste_type.wt_desc IS
    'waste type description';

ALTER TABLE waste_type ADD CONSTRAINT waste_type_pk PRIMARY KEY ( wt_id );

ALTER TABLE bin_collected
    ADD CONSTRAINT bin_bincollected FOREIGN KEY ( bin_rfid )
        REFERENCES bin ( bin_rfid );

ALTER TABLE contract_pricing
    ADD CONSTRAINT bintype_contractpricing FOREIGN KEY ( bt_size,
                                                         wt_id )
        REFERENCES bin_type ( bt_size,
                              wt_id );

ALTER TABLE bin_collected
    ADD CONSTRAINT collection_bincollected FOREIGN KEY ( collection_id )
        REFERENCES collection ( collection_id );

ALTER TABLE contract_collection
    ADD CONSTRAINT contract_contractcollection FOREIGN KEY ( contract_no )
        REFERENCES contract ( contract_no );

ALTER TABLE contract_pricing
    ADD CONSTRAINT contract_contractpricing FOREIGN KEY ( contract_no )
        REFERENCES contract ( contract_no );

ALTER TABLE collection
    ADD CONSTRAINT contractcollection_collection FOREIGN KEY ( contract_no,
                                                               wt_id )
        REFERENCES contract_collection ( contract_no,
                                         wt_id );

ALTER TABLE bin
    ADD CONSTRAINT contractpricing_bin FOREIGN KEY ( bt_size,
                                                     wt_id,
                                                     contract_no )
        REFERENCES contract_pricing ( bt_size,
                                      wt_id,
                                      contract_no );

ALTER TABLE driver_truck
    ADD CONSTRAINT driver_driver_truck FOREIGN KEY ( driver_no )
        REFERENCES driver ( driver_no );

ALTER TABLE collection
    ADD CONSTRAINT drivertruck_collection FOREIGN KEY ( driver_no,
                                                        truck_vin )
        REFERENCES driver_truck ( driver_no,
                                  truck_vin );

ALTER TABLE contract
    ADD CONSTRAINT localauthority_contract FOREIGN KEY ( la_name )
        REFERENCES local_authority ( la_name );

ALTER TABLE street
    ADD CONSTRAINT localauthority_street FOREIGN KEY ( la_name )
        REFERENCES local_authority ( la_name );

ALTER TABLE bin
    ADD CONSTRAINT property_bin FOREIGN KEY ( prop_id )
        REFERENCES property ( prop_id );

ALTER TABLE owner
    ADD CONSTRAINT property_owner FOREIGN KEY ( prop_id )
        REFERENCES property ( prop_id );

ALTER TABLE property
    ADD CONSTRAINT street_property FOREIGN KEY ( st_id,
                                                 la_name )
        REFERENCES street ( st_id,
                            la_name );

ALTER TABLE driver_truck
    ADD CONSTRAINT truck_driver_truck FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE bin_type
    ADD CONSTRAINT wastetype_bintype FOREIGN KEY ( wt_id )
        REFERENCES waste_type ( wt_id );

ALTER TABLE contract_collection
    ADD CONSTRAINT wastetype_contractcollection FOREIGN KEY ( wt_id )
        REFERENCES waste_type ( wt_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL off
set echo off